const fs = require("fs");
const { convert } = require("./pinyin2zhuyin.js");
const ENRICH_PATH = __dirname + "/enrich.json";

const G = { hanzi: "個", zhuyin: "ㄍㄜˋ", pinyin: "gè" };   // general measure for people
const W = { hanzi: "位", zhuyin: "ㄨㄟˋ", pinyin: "wèi" };  // polite measure for people

// [num, hanzi, pinyin(syllable-spaced, no punctuation), en, measure|null]
const BATCH = [
  [241, "現在氣溫是零度。", "xiàn zài qì wēn shì líng dù", "The temperature is zero degrees now.", null],
  [242, "我只要一個。", "wǒ zhǐ yào yí ge", "I only want one.", null],
  [243, "二加二等於四。", "èr jiā èr děng yú sì", "Two plus two equals four.", null],
  [244, "我有三個兄弟。", "wǒ yǒu sān ge xiōng dì", "I have three brothers.", null],
  [245, "一年有四季。", "yì nián yǒu sì jì", "There are four seasons in a year.", null],
  [246, "我五點下班。", "wǒ wǔ diǎn xià bān", "I get off work at five.", null],
  [247, "這班公車六點發車。", "zhè bān gōng chē liù diǎn fā chē", "This bus leaves at six.", null],
  [248, "一個星期有七天。", "yí ge xīng qī yǒu qī tiān", "There are seven days in a week.", null],
  [249, "商店八點開門。", "shāng diàn bā diǎn kāi mén", "The shop opens at eight.", null],
  [250, "我晚上九點睡覺。", "wǒ wǎn shàng jiǔ diǎn shuì jiào", "I go to sleep at nine.", null],
  [251, "這裡有十個人。", "zhè lǐ yǒu shí ge rén", "There are ten people here.", null],
  [252, "這件衣服一百塊。", "zhè jiàn yī fú yì bǎi kuài", "This shirt is a hundred dollars.", null],
  [253, "這雙鞋要三千塊。", "zhè shuāng xié yào sān qiān kuài", "These shoes cost three thousand dollars.", null],
  [254, "這台電腦要三萬塊。", "zhè tái diàn nǎo yào sān wàn kuài", "This computer costs thirty thousand dollars.", null],
  [255, "她是第一個到的。", "tā shì dì yī ge dào de", "She was the first to arrive.", null],
  [256, "請看第二頁。", "qǐng kàn dì èr yè", "Please look at the second page.", null],
  [257, "我只吃了半碗飯。", "wǒ zhǐ chī le bàn wǎn fàn", "I only ate half a bowl of rice.", null],
  [258, "我今天沒有時間。", "wǒ jīn tiān méi yǒu shí jiān", "I don't have time today.", null],
  [259, "車程大概一個小時。", "chē chéng dà gài yí ge xiǎo shí", "The ride takes about an hour.", null],
  [260, "請等我五分鐘。", "qǐng děng wǒ wǔ fēn zhōng", "Please wait five minutes for me.", null],
  [261, "再等我幾秒。", "zài děng wǒ jǐ miǎo", "Wait a few more seconds for me.", null],
  [262, "今天天氣很好。", "jīn tiān tiān qì hěn hǎo", "The weather is nice today.", null],
  [263, "明天見。", "míng tiān jiàn", "See you tomorrow.", null],
  [264, "我昨天去了夜市。", "wǒ zuó tiān qù le yè shì", "I went to the night market yesterday.", null],
  [265, "我早上喝咖啡。", "wǒ zǎo shàng hē kā fēi", "I drink coffee in the morning.", null],
  [266, "我們中午一起吃飯。", "wǒ men zhōng wǔ yì qǐ chī fàn", "We eat lunch together at noon.", null],
  [267, "我下午有一個會議。", "wǒ xià wǔ yǒu yí ge huì yì", "I have a meeting in the afternoon.", null],
  [268, "我晚上在家看電影。", "wǒ wǎn shàng zài jiā kàn diàn yǐng", "I watch movies at home in the evening.", null],
  [269, "他半夜才回家。", "tā bàn yè cái huí jiā", "He didn't get home until midnight.", null],
  [270, "我下星期要出差。", "wǒ xià xīng qī yào chū chāi", "I'm going on a business trip next week.", null],
  [271, "週末我想去爬山。", "zhōu mò wǒ xiǎng qù pá shān", "I want to go hiking this weekend.", null],
  [272, "星期一我要上班。", "xīng qī yī wǒ yào shàng bān", "I have to work on Monday.", null],
  [273, "星期二有中文課。", "xīng qī èr yǒu zhōng wén kè", "There's a Chinese class on Tuesday.", null],
  [274, "我們星期三開會。", "wǒ men xīng qī sān kāi huì", "We have a meeting on Wednesday.", null],
  [275, "我星期四要看醫生。", "wǒ xīng qī sì yào kàn yī shēng", "I'm seeing a doctor on Thursday.", null],
  [276, "星期五晚上一起吃飯吧。", "xīng qī wǔ wǎn shàng yì qǐ chī fàn ba", "Let's have dinner together on Friday evening.", null],
  [277, "星期六銀行沒開。", "xīng qī liù yín háng méi kāi", "The bank isn't open on Saturday.", null],
  [278, "我星期日通常在家休息。", "wǒ xīng qī rì tōng cháng zài jiā xiū xí", "I usually rest at home on Sunday.", null],
  [279, "下個月我要搬家。", "xià ge yuè wǒ yào bān jiā", "I'm moving next month.", null],
  [280, "我在台灣住了三年。", "wǒ zài tái wān zhù le sān nián", "I've lived in Taiwan for three years.", null],
  [281, "請確認一下日期。", "qǐng què rèn yí xià rì qī", "Please confirm the date.", null],
  [282, "今天是我朋友的生日。", "jīn tiān shì wǒ péng yǒu de shēng rì", "Today is my friend's birthday.", null],
  [283, "現在幾點？", "xiàn zài jǐ diǎn", "What time is it now?", null],
  [284, "請等一下，我馬上來。", "qǐng děng yí xià wǒ mǎ shàng lái", "Please wait a moment, I'll be right there.", null],
  [285, "他每天都準時到公司。", "tā měi tiān dōu zhǔn shí dào gōng sī", "He arrives at the office on time every day.", null],
  [286, "今天塞車，所以我遲到了。", "jīn tiān sāi chē suǒ yǐ wǒ chí dào le", "There was traffic today, so I was late.", null],
  [287, "我們提早十分鐘到了。", "wǒ men tí zǎo shí fēn zhōng dào le", "We arrived ten minutes early.", null],
  [288, "你學中文多久了？", "nǐ xué zhōng wén duō jiǔ le", "How long have you been learning Chinese?", null],
  [289, "我買了一個麵包。", "wǒ mǎi le yí ge miàn bāo", "I bought a loaf of bread.", null],
  [290, "門口有一位客人。", "mén kǒu yǒu yí wèi kè rén", "There's a guest at the door.", null],
  [291, "前面有一條路。", "qián miàn yǒu yì tiáo lù", "There's a road ahead.", null],
  [292, "我要買兩張票。", "wǒ yào mǎi liǎng zhāng piào", "I want to buy two tickets.", null],
  [293, "我借了三本書。", "wǒ jiè le sān běn shū", "I borrowed three books.", null],
  [294, "辦公室有五台電腦。", "bàn gōng shì yǒu wǔ tái diàn nǎo", "There are five computers in the office.", null],
  [295, "我想喝一杯咖啡。", "wǒ xiǎng hē yì bēi kā fēi", "I'd like a cup of coffee.", null],
  [296, "我買了一件外套。", "wǒ mǎi le yí jiàn wài tào", "I bought a jacket.", null],
  [297, "附近有一間咖啡店。", "fù jìn yǒu yì jiān kā fēi diàn", "There's a café nearby.", null],
  [298, "門口停了一輛車。", "mén kǒu tíng le yí liàng chē", "There's a car parked at the door.", null],
  [299, "我需要一雙新鞋。", "wǒ xū yào yì shuāng xīn xié", "I need a new pair of shoes.", null],
  [300, "我去過台南兩次。", "wǒ qù guò tái nán liǎng cì", "I've been to Tainan twice.", null],
  [301, "這家店有很多種茶。", "zhè jiā diàn yǒu hěn duō zhǒng chá", "This shop has many kinds of tea.", null],
  [302, "我吃了兩顆蘋果。", "wǒ chī le liǎng kē píng guǒ", "I ate two apples.", null],
  [303, "請給我一支筆。", "qǐng gěi wǒ yì zhī bǐ", "Please give me a pen.", null],
  [304, "房間裡有四把椅子。", "fáng jiān lǐ yǒu sì bǎ yǐ zi", "There are four chairs in the room.", null],
  [305, "我早餐吃了兩片吐司。", "wǒ zǎo cān chī le liǎng piàn tǔ sī", "I ate two slices of toast for breakfast.", null],
  [306, "請給我一塊蛋糕。", "qǐng gěi wǒ yí kuài dàn gāo", "Please give me a piece of cake.", null],
  [307, "我買了一盒水餃。", "wǒ mǎi le yì hé shuǐ jiǎo", "I bought a box of dumplings.", null],
  [308, "桌上有三瓶水。", "zhuō shàng yǒu sān píng shuǐ", "There are three bottles of water on the table.", null],
  [309, "我們點了兩盤菜。", "wǒ men diǎn le liǎng pán cài", "We ordered two plates of food.", null],
  [310, "他買了一套西裝。", "tā mǎi le yí tào xī zhuāng", "He bought a suit.", null],
  [311, "我收到一封電子郵件。", "wǒ shōu dào yì fēng diàn zǐ yóu jiàn", "I received an email.", null],
  [312, "老師要我們寫一篇文章。", "lǎo shī yào wǒ men xiě yì piān wén zhāng", "The teacher asked us to write an essay.", null],
  [313, "我週末看了兩部電影。", "wǒ zhōu mò kàn le liǎng bù diàn yǐng", "I watched two movies over the weekend.", null],
  [314, "辦公室在十二層。", "bàn gōng shì zài shí èr céng", "The office is on the twelfth floor.", null],
  [315, "這裡有很多人。", "zhè lǐ yǒu hěn duō rén", "There are a lot of people here.", G],
  [316, "大家都到了嗎？", "dà jiā dōu dào le ma", "Is everyone here?", null],
  [317, "別管別人怎麼想。", "bié guǎn bié rén zěn me xiǎng", "Don't worry about what others think.", null],
  [318, "他是我的好朋友。", "tā shì wǒ de hǎo péng yǒu", "He's my good friend.", G],
  [319, "她是我的大學同學。", "tā shì wǒ de dà xué tóng xué", "She's my university classmate.", G],
  [320, "我跟同事一起吃午餐。", "wǒ gēn tóng shì yì qǐ chī wǔ cān", "I have lunch with my coworkers.", G],
  [321, "我的鄰居很友善。", "wǒ de lín jū hěn yǒu shàn", "My neighbor is friendly.", G],
  [322, "今天店裡有很多客人。", "jīn tiān diàn lǐ yǒu hěn duō kè rén", "There are many customers in the shop today.", W],
  [323, "不要跟陌生人走。", "bú yào gēn mò shēng rén zǒu", "Don't go with strangers.", G],
  [324, "我很愛我的家人。", "wǒ hěn ài wǒ de jiā rén", "I love my family very much.", null],
  [325, "他有一個幸福的家庭。", "tā yǒu yí ge xìng fú de jiā tíng", "He has a happy family.", G],
  [326, "我爸爸是老師。", "wǒ bà ba shì lǎo shī", "My dad is a teacher.", G],
  [327, "我媽媽很會煮菜。", "wǒ mā ma hěn huì zhǔ cài", "My mom is a great cook.", G],
  [328, "我的父母住在台南。", "wǒ de fù mǔ zhù zài tái nán", "My parents live in Tainan.", null],
  [329, "他有一個兒子。", "tā yǒu yí ge ér zi", "He has a son.", G],
  [330, "他們的女兒很可愛。", "tā men de nǚ ér hěn kě ài", "Their daughter is cute.", G],
  [331, "我哥哥比我大三歲。", "wǒ gē ge bǐ wǒ dà sān suì", "My older brother is three years older than me.", G],
  [332, "我弟弟還在念書。", "wǒ dì di hái zài niàn shū", "My younger brother is still in school.", G],
  [333, "我姊姊在銀行工作。", "wǒ jiě jie zài yín háng gōng zuò", "My older sister works at a bank.", G],
  [334, "我妹妹很喜歡畫畫。", "wǒ mèi mei hěn xǐ huān huà huà", "My little sister loves drawing.", G],
  [335, "她的丈夫是醫生。", "tā de zhàng fū shì yī shēng", "Her husband is a doctor.", G],
  [336, "王先生的太太很親切。", "wáng xiān shēng de tài tai hěn qīn qiè", "Mr. Wang's wife is very kind.", W],
  [337, "她有男朋友了。", "tā yǒu nán péng yǒu le", "She has a boyfriend now.", G],
  [338, "他跟女朋友去看電影。", "tā gēn nǚ péng yǒu qù kàn diàn yǐng", "He went to a movie with his girlfriend.", G],
  [339, "她是我最好的伴侶。", "tā shì wǒ zuì hǎo de bàn lǚ", "She's my best partner.", G],
  [340, "過年時親戚都會來。", "guò nián shí qīn qī dōu huì lái", "Relatives all come during New Year.", G],
  [341, "我爺爺今年八十歲。", "wǒ yé ye jīn nián bā shí suì", "My grandpa is eighty this year.", W],
  [342, "我奶奶很會做菜。", "wǒ nǎi nai hěn huì zuò cài", "My grandma is a great cook.", W],
  [343, "我外公住在鄉下。", "wǒ wài gōng zhù zài xiāng xià", "My maternal grandpa lives in the countryside.", W],
  [344, "我外婆做的菜很好吃。", "wǒ wài pó zuò de cài hěn hǎo chī", "The food my maternal grandma makes is delicious.", W],
  [345, "我們的老師很有耐心。", "wǒ men de lǎo shī hěn yǒu nài xīn", "Our teacher is very patient.", W],
  [346, "這個班有三十個學生。", "zhè ge bān yǒu sān shí ge xué shēng", "There are thirty students in this class.", G],
  [347, "我下午要去看醫生。", "wǒ xià wǔ yào qù kàn yī shēng", "I'm going to see a doctor this afternoon.", W],
  [348, "護士幫我量了體溫。", "hù shì bāng wǒ liáng le tǐ wēn", "The nurse took my temperature.", W],
  [349, "我們老闆人很好。", "wǒ men lǎo bǎn rén hěn hǎo", "Our boss is a good person.", W],
  [350, "這件事要問主管。", "zhè jiàn shì yào wèn zhǔ guǎn", "You need to ask the supervisor about this.", W],
  [351, "這家公司有一百個員工。", "zhè jiā gōng sī yǒu yì bǎi ge yuán gōng", "This company has a hundred employees.", G],
  [352, "他是一位軟體工程師。", "tā shì yí wèi ruǎn tǐ gōng chéng shī", "He's a software engineer.", W],
  [353, "計程車司機很親切。", "jì chéng chē sī jī hěn qīn qiè", "The taxi driver was very kind.", W],
  [354, "店員幫我找到了尺寸。", "diàn yuán bāng wǒ zhǎo dào le chǐ cùn", "The clerk helped me find the size.", G],
  [355, "有問題可以找警察。", "yǒu wèn tí kě yǐ zhǎo jǐng chá", "You can find a police officer if you have a problem.", W],
  [356, "房東下週會來。", "fáng dōng xià zhōu huì lái", "The landlord is coming next week.", G],
  [357, "這位房客住了兩年。", "zhè wèi fáng kè zhù le liǎng nián", "This tenant has lived here for two years.", G],
  [358, "這位顧客想要退貨。", "zhè wèi gù kè xiǎng yào tuì huò", "This customer wants to return an item.", W],
  [359, "我想跟經理談一談。", "wǒ xiǎng gēn jīng lǐ tán yì tán", "I'd like to talk with the manager.", W],
  [360, "我們的團隊合作得很好。", "wǒ men de tuán duì hé zuò de hěn hǎo", "Our team works well together.", G],
  [361, "他們的關係很好。", "tā men de guān xì hěn hǎo", "They have a good relationship.", null],
  [362, "他們的婚姻很幸福。", "tā men de hūn yīn hěn xìng fú", "They have a happy marriage.", null]
];

const enrich = fs.existsSync(ENRICH_PATH) ? JSON.parse(fs.readFileSync(ENRICH_PATH, "utf8")) : {};
let bad = 0;
for (const [num, hanzi, pinyin, en, measure] of BATCH) {
  const zhuyin = convert(pinyin);
  if (zhuyin.indexOf("null") >= 0) { console.error("BAD:", num, pinyin, "->", zhuyin); bad++; continue; }
  enrich[String(num)] = { example: { hanzi, zhuyin, pinyin, en }, measure: measure || null };
}
if (bad) { console.error(bad, "bad conversions — aborting"); process.exit(1); }
fs.writeFileSync(ENRICH_PATH, JSON.stringify(enrich, null, 1));
console.log("added", BATCH.length, "; total enriched:", Object.keys(enrich).length);
